version: "3.9"
services:
  ticket:
    container_name: ticket
    ports:
      - 8060:8000
    build:
      context: ./docker/php
      dockerfile: ./Dockerfile
    environment:
      - PHP_MEMORY_LIMIT=512M
      - NODE_ENV=development
    networks:
      - public
    volumes:
      - ./:/var/www/html
    restart: always  # Adiciona política de reinício

networks:
  public:
    name: public
    external: true

